// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALI-PvU81i2AswvaKHknrjRJtHVubLTxc',
    appId: '1:116336198730:web:7a48d2ab1d0b48a75492b3',
    messagingSenderId: '116336198730',
    projectId: 'brooon-8cba6',
    authDomain: 'brooon-8cba6.firebaseapp.com',
    storageBucket: 'brooon-8cba6.appspot.com',
    measurementId: 'G-BGX6G27731',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRZjlPygkKCcNg1_sMSoPEovHsZZcEAZM',
    appId: '1:116336198730:android:2bb65fbe8b4262655492b3',
    messagingSenderId: '116336198730',
    projectId: 'brooon-8cba6',
    storageBucket: 'brooon-8cba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6tc2b57adxvrBcDtB7WB-yQlw6SuBb-I',
    appId: '1:116336198730:ios:0734e2eed7a99ac95492b3',
    messagingSenderId: '116336198730',
    projectId: 'brooon-8cba6',
    storageBucket: 'brooon-8cba6.appspot.com',
    iosClientId: '116336198730-opshbccng2vapv3bg4na8epl5bt6fqpn.apps.googleusercontent.com',
    iosBundleId: 'com.brooon.app',
  );
}
